version: '3.1'

services:
  web:
    build: .
    ports:
      - "8069:8069"
    environment:
      - DB_HOST=postgres.railway.internal
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=NvJyEvYMctLHafIAfmENdzicrryxUxxf
      - DB_NAME=railway