version: '3.1'

services:
  web:
    build: .
    ports:
      - "8069:8069"
    environment:
      - DATABASE_URL=postgres://postgres:NvJyEvYMctLHafIAfmENdzicrryxUxxf@postgres.railway.internal:5432/railway