version: '3.1'

services:
  web:
    build: .
    ports:
      - "8069:8069"
    environment:
      - HOST=postgres.railway.internal
      - USER=postgres
      - PASSWORD=NvJyEvYMctLHafIAfmENdzicrryxUxxf
      - POSTGRES_DB=railway
