version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    ports:
      - "5432:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      ODOO_DATABASE_HOST: db
      ODOO_DATABASE_PORT: 5432
      ODOO_DATABASE_USER: odoo
      ODOO_DATABASE_PASSWORD: odoo
      ODOO_DATABASE_NAME: odoo
    volumes:
      - ./addons:/mnt/extra-addons
    restart: always

volumes:
  odoo-db-data:
